# Generated by Django 3.0.3 on 2020-02-19 20:44

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CreateExtension("postgis"),
    ]
